//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AthleticsSocialWeb.Core.Entities.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog_Error
    {
        public int Id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public string host { get; set; }
        public string type { get; set; }
        public string source { get; set; }
        public string message { get; set; }
        public string level { get; set; }
        public string logger { get; set; }
        public string stacktrace { get; set; }
        public string allxml { get; set; }
    }
}
